### PR TITLE
update to HC beta

### LINKED ISSUE #25: Get App to Compile and Run under Holochain Beta

### PR DESCRIPTION
**Pull request by dauphin3**
#25

### CODE REVIEW

**Comment by evomimic** [comment]
Hey Zeek... glad to see MAP Proto apparently working under holochain beta, but also a bit confused. Both you and @nphias previously reported errors trying to get MAP Proto to build under holochain versions later than 0.0.136. And yet, it appears to be magically working now without you having to change anything. Whenever things start "magically working" it always makes me a bit nervous that they can also "magically stop working" in the future. 

Do you have any clues as to why it works now?

**Comment by dauphin3** [comment]
yes I'm fairly sure that's because its not connecting to a conductor. Its important to note an upgrade to Nix and the HC binaries is required.  There is now native mac support for nix and so thus I no longer had to use my special i386
(intel compatible mode) terminal.  I ended up having to uninstall and reinstall Nix.
now added flake per instructions nphias gave

**Comment by nphias** [comment]
Hey Zeek.. glad you were able to upgrade nix and use hc natively.. I have done all the upgrade work in the beta01-upgrade branch .. could you work from that branch? No need to duplicate work .. thanks

**Review by evomimic — APPROVED** [review]
Seems to compile under Holochain beta. Zeek did diff between this branch and beta_01_release_upgrade branch and couldn't really identify reason why Thomas is getting duplicate __num_entry_types error. 

Approving this pull request to carry on with dev. Will re-open if Thomas is still encountering the error.

**Review by evomimic — APPROVED** [review]

**Pull request merged**
